---
- name: Add nginx repository to OS
  yum_repository:
    name: nginx
    state: present
    gpgkey: "{{ NGINX_GPG_KEY_URL }}"
    gpgcheck: yes
    enabled: yes
    description: "nginx repo"
    baseurl: "http://nginx.org/packages/mainline/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/"
  become: yes

- name: Add RPM key for NGINX
  rpm_key:
    key: "{{ NGINX_GPG_KEY_URL }}"
    state: present
  become: yes


- name: Install nginx 
  package:
    name: nginx
    state: present
  become: yes

- name: Create directory structure for nginx
  file:
    path: /etc/nginx/conf.d/http/
    state: directory
  become: yes

- name: Create a group allowing editing web content
  group:
    name: webeditors
    state: present
  become: yes

- name: Create directory for web content
  file:
    path: /www/
    owner: root
    group: webeditors
    mode: 0775
    state: directory
    setype: httpd_config_t
  become: yes

# TODO move defaults to its section
- name: Create top-level Nginx configuration for webserver
  template:
    src: general_nginx_conf.j2
    dest: /etc/nginx/nginx.conf
    validate: /usr/sbin/nginx -c %s -t
    backup: yes
  become: yes