- name: Allow ESTABLISHED and RELATED connections
  iptables:
    chain: INPUT
    ctstate:
      - ESTABLISHED
      - RELATED
    jump: ACCEPT
    state: present
    comment: "Allow ESTABLISHED and RELATED connections"
  become: yes

- name: Allow new SSH connection to host
  iptables:
    chain: INPUT
    ctstate:
      - NEW
    jump: ACCEPT
    state: present
    protocol: tcp
    destination_port: 22
    comment: "Allow SSH connection to host"
  become: yes

- name: Allow localhost traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    in_interface: "{{ ansible_facts.lo.device }}"
  become: yes

- name: Allow ICMP traffic
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: icmp
    icmp_type: "echo-request"
  become: yes

- name: Set input policy to DROP
  iptables:
    chain: INPUT
    policy: DROP
  become: yes