- name: Disable firewalld on Centos 7
  service:
    name: firewalld
    enabled: no
    state: stopped
  become: yes
  ignore_errors: yes # If the case is that firewalld is not installed, don't let ansible crash (DigitalOcean doesn't have it installed)

- name: Install iptables-services on Centos 7
  yum:
    name: iptables-services
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "OracleLinux"
  become: yes

- include: inbound_rules.yml
- include: outbound_rules.yml


- name: Save the iptables configuration
  command: service iptables save
  become: yes

- name: Turn on iptables service
  service:
    name: iptables.service
    state: started
    enabled: yes
  become: yes
