- hosts: all
  remote_user: docker_operator # User with membership in docker group
  name: Deploy local version of Jekyll blog to server and start web server

  tasks:
  - name: Ensure, dependencies are installed on host # Makes sure that remote_user have docker-py installed
    pip:
      name: docker-py
      state: present
      extra_args: --user

  - name: Deploy blog on NGINX
    include_role:
      name: nginx-blog