- name: Gather OS facts for role
  include_vars: 
    file: "{{ item }}"
  loop: 
    - "{{ ansible_os_family | lower }}.yml"

- name: Install dependecies
  package:
    name: "{{ docker_dependencies }}"
    state: present
  become: yes

- name: add docker repository | RedHat
  yum_repository:
    name: docker-ce-stable
    description: "Docker CE Stable - $basearch"
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    enabled: yes
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution != "OracleLinux"

- name: Install Docker
  yum:
    name: docker-ce
    state: latest
    update_cache: yes
  become: yes

- name: Enable and start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Make sure group docker is created
  group:
    name: docker
    state: present
  become: yes

- name: Create Docker user and add him to group Docker group
  user:
    name: "{{ docker_user_name }}"
    comment: User for managing containers
    group: docker
    password: "{{ docker_user_password }}" # already hashed with salted SHA512 - Jinja2 filters doesn't work on Vault values
  become: yes

- name: Make sure .ssh is created for user
  file:
    path: "/home/{{ docker_user_name }}/.ssh/"
    owner: "{{ docker_user_name }}"
    mode: 0700 # rwx------
    state: directory
    setype: _default # will put seuser type for SELinux
  become: yes

- name: Copy public key to machine for passwordless login
  copy:
    src: '/home/lukas/.ssh/id_rsa_passwordless.pub'
    dest: '/home/{{ docker_user_name }}/.ssh/authorized_keys' # This will override all known authorized keys
    mode: 0600 # rw-------
    owner: "{{ docker_user_name }}"
    setype: _default # will put seuser type for SELinux
  become: yes