---
- hosts: auto_web
  gather_facts: True
  tasks:
    - name: Create Web Server on Centos 7
      import_role:
        name: webserver

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Rebuild Jekyll site in Docker container on localhost
      docker_container:
        name: jekyll_builder
        image: jekyll/jekyll
        volumes:
          - "/home/lukas/blog/jekyll-blog/:/srv/jekyll"
          - "/home/lukas/blog/jekyll-blog/vendor/:/usr/local/bundle"
        command: "jekyll build --destination /home/lukas/blog/jekyll-blog/"
        state: started

- hosts: auto_web
  gather_facts: False
  tasks:
    - name: Copy generated site to webserver
      copy:
        src: "/home/lukas/blog/jekyll-blog/_site/"
        dest: "/www/blog/"
        setype: httpd_config_t
        owner: vagrant
        group: webeditors
      become: yes
...